/**
 * Row types for the Crowned by Nat schema.
 *
 * Hand written rather than generated by `supabase gen types`, because that
 * command needs a project ref and a login, and this repo has to typecheck on a
 * clean clone with no Supabase account attached. They mirror
 * supabase/migrations/0001_crown_by_nat_foundation.sql exactly; if you change a
 * column there, change it here in the same commit.
 */

export type UserRole = "customer" | "admin";

export type AppointmentStatus =
  | "pending"
  | "confirmed"
  | "completed"
  | "cancelled"
  | "rescheduled";

/** Order is the order they appear in the admin status control. */
export const APPOINTMENT_STATUSES: AppointmentStatus[] = [
  "pending",
  "confirmed",
  "completed",
  "rescheduled",
  "cancelled",
];

/** Statuses that still occupy a slot, matching the partial index in SQL. */
export const LIVE_STATUSES: AppointmentStatus[] = [
  "pending",
  "confirmed",
  "rescheduled",
];

export type Profile = {
  id: string;
  email: string;
  full_name: string | null;
  phone: string | null;
  role: UserRole;
  created_at: string;
  updated_at: string;
};

export type Location = {
  id: string;
  slug: string;
  name: string;
  city: string;
  state: string;
  active: boolean;
  display_order: number;
  created_at: string;
  updated_at: string;
};

export type Service = {
  id: string;
  slug: string;
  name: string;
  description: string;
  price_cents: number | null;
  duration_minutes: number | null;
  pricing_confirmed: boolean;
  active: boolean;
  display_order: number;
  created_at: string;
  updated_at: string;
};

export type Appointment = {
  id: string;
  reference: string;
  customer_id: string | null;
  guest_name: string | null;
  guest_email: string | null;
  guest_phone: string | null;
  service_id: string;
  location_id: string;
  /**
   * Frozen at booking time. ALWAYS read the display name from here rather than
   * joining to locations: that is the whole reason the column exists, and a
   * join would reintroduce the bug it was added to prevent (an old Towson
   * appointment relabelling itself after Nat switches the site to Laurel).
   */
  service_name_snapshot: string;
  location_name_snapshot: string;
  price_cents_snapshot: number | null;
  appointment_date: string;
  appointment_time: string;
  duration_minutes: number;
  starts_at: string;
  ends_at: string;
  status: AppointmentStatus;
  notes: string | null;
  reschedule_requested_at: string | null;
  reschedule_note: string | null;
  admin_note: string | null;
  created_at: string;
  updated_at: string;
};

/** An appointment with the booking customer's profile joined in, for admin. */
export type AppointmentWithCustomer = Appointment & {
  profiles: Pick<Profile, "id" | "full_name" | "email" | "phone"> | null;
};

/** Shape returned by the public.booked_slots() RPC. */
export type BookedSlot = {
  slot_time: string;
  slot_minutes: number;
};

/** Shape returned by the public.create_guest_appointment() RPC. */
export type GuestBookingReceipt = {
  reference: string;
  service: string;
  location: string;
  date: string;
  time: string;
  duration: number;
  price_cents: number | null;
  status: AppointmentStatus;
};

/** Shape returned by the public.admin_stats() RPC. */
export type AdminStats = {
  upcoming: number;
  pending: number;
  reschedule_requests: number;
  completed_this_month: number;
  customers: number;
  guest_bookings: number;
};
